/* The 24 residents of RT 04 (spec §8.1). Households share a home; schedules are
   written as [time, location, activity] steps (see schedule.ts). */
import type { AppearanceParams, Topic, Trait, WeekSchedule } from './types';
import { week, overlay } from './schedule';

export interface ResidentDef {
  id: string;
  name: string;
  address: string;
  age: number;
  gender: 'm' | 'f';
  occupation: string;
  birthday: string;
  household: string;
  traits: Trait[];
  likes: Topic[];
  dislikes: Topic[];
  schedule: WeekSchedule;
  /** Starting friendship with Raka; some elders remember him as a kid. */
  friendship?: number;
  look?: Partial<AppearanceParams>;
  /** Relative walking pace (1 = 1.3 m/s). */
  pace?: number;
}

export const RESIDENTS: ResidentDef[] = [
  {
    id: 'bambang',
    name: 'Pak Bambang',
    address: 'Pak RT',
    age: 56,
    gender: 'm',
    occupation: 'Ketua RT, retired bank clerk',
    birthday: '3 Februari',
    household: 'rt',
    traits: ['caring', 'ambitious'],
    likes: ['kampung news', 'football', 'old days'],
    dislikes: ['gossip'],
    friendship: 10,
    look: { hair: 'peci', top: '#e8e4da', longSleeves: true },
    schedule: week({
      weekday: [
        ['06:00', 'home.teras', 'relax'],
        ['07:15', 'warung.customer', 'shop'],
        ['07:45', 'balai.desk', 'work'],
        ['11:40', 'musholla.inside', 'pray'],
        ['12:20', 'home.inside', 'home'],
        ['15:30', 'balai.board', 'work'],
        ['16:15', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['21:30', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'lapangan.bench', 'relax'],
        ['07:30', 'warung.bench', 'chat'],
        ['09:00', 'balai.desk', 'work'],
        ['11:00', 'home.teras', 'relax'],
        ['12:00', 'home.inside', 'home'],
        ['16:00', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['21:30', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [2, 5],
    }),
  },
  {
    id: 'ratna',
    name: 'Bu Ratna',
    address: 'Bu RT',
    age: 52,
    gender: 'f',
    occupation: 'Sells kue from home, runs the arisan',
    birthday: '21 April',
    household: 'rt',
    traits: ['cheerful', 'gossip'],
    likes: ['food', 'family', 'kampung news'],
    dislikes: ['football'],
    friendship: 5,
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:00', 'home.inside', 'work'],
        ['09:00', 'home.teras', 'work'],
        ['11:00', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'chat'],
        ['16:30', 'warung.customer', 'shop'],
        ['17:00', 'home.inside', 'home'],
        ['21:00', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['07:00', 'pasar.customer', 'shop'],
        ['08:00', 'warung.bench', 'chat'],
        ['09:00', 'home.teras', 'chat'],
        ['11:00', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'chat'],
        ['17:00', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'sri',
    name: 'Bu Sri',
    address: 'Bu',
    age: 48,
    gender: 'f',
    occupation: 'Owner of Warung Bu Sri',
    birthday: '17 Mei',
    household: 'sri',
    traits: ['gossip', 'caring'],
    likes: ['gossip', 'market prices', 'family'],
    dislikes: ['motorbikes'],
    look: { hair: 'hijab', headwear: '#c9d6cf', top: '#3a9a73' },
    schedule: week({
      weekday: [
        ['06:00', 'warung.owner', 'work'],
        ['12:30', 'warungHome.inside', 'home'],
        ['13:15', 'warung.owner', 'work'],
        ['17:45', 'warungHome.inside', 'pray'],
        ['18:30', 'warung.owner', 'work'],
        ['21:30', 'warungHome.inside', 'sleep'],
      ],
    }),
  },
  {
    id: 'dimas',
    name: 'Dimas',
    address: 'Dek',
    age: 16,
    gender: 'm',
    occupation: 'SMA student, helps at the warung',
    birthday: '9 September',
    household: 'sri',
    traits: ['shy', 'sporty'],
    likes: ['football', 'motorbikes', 'music'],
    dislikes: ['religion'],
    pace: 1.1,
    schedule: week({
      weekday: [
        ['06:00', 'warung.helper', 'work'],
        ['06:35', 'away', 'study'],
        ['14:30', 'warung.helper', 'work'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:45', 'musholla.inside', 'pray'],
        ['18:30', 'warung.helper', 'work'],
        ['20:30', 'warungHome.inside', 'sleep'],
      ],
      sat: [
        ['06:00', 'warungHome.inside', 'sleep'],
        ['08:00', 'warung.helper', 'work'],
        ['11:00', 'lapangan.field', 'play'],
        ['12:30', 'warungHome.inside', 'home'],
        ['15:30', 'lapangan.field', 'play'],
        ['17:45', 'warung.helper', 'work'],
        ['20:30', 'meja.seat', 'chat'],
        ['22:00', 'warungHome.inside', 'sleep'],
      ],
      jumatan: true,
    }),
  },
  {
    id: 'darto',
    name: 'Pak Darto',
    address: 'Pak',
    age: 74,
    gender: 'm',
    occupation: 'Retired carpenter',
    birthday: '12 Januari',
    household: 'darto',
    traits: ['grumpy', 'caring'],
    likes: ['old days', 'religion', 'weather'],
    dislikes: ['music', 'motorbikes'],
    friendship: 20,
    pace: 0.75,
    look: { hair: 'peci', top: '#6b5a45', longSleeves: true },
    schedule: week({
      weekday: [
        ['06:00', 'home.teras', 'relax'],
        ['07:00', 'warung.bench', 'eat'],
        ['08:30', 'kebun.plot', 'garden'],
        ['11:40', 'musholla.inside', 'pray'],
        ['12:30', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'home.teras', 'relax'],
        ['20:30', 'home.inside', 'sleep'],
      ],
      jumatan: true,
    }),
  },
  {
    id: 'sumi',
    name: 'Bu Darto',
    address: 'Bu',
    age: 70,
    gender: 'f',
    occupation: 'Retired, keeps the house',
    birthday: '28 Juni',
    household: 'darto',
    traits: ['caring', 'cheerful'],
    likes: ['family', 'food', 'old days'],
    dislikes: ['gossip'],
    friendship: 20,
    pace: 0.75,
    look: { hair: 'hijab', headwear: '#e8c9bd' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:00', 'home.inside', 'home'],
        ['10:00', 'home.teras', 'relax'],
        ['12:00', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'chat'],
        ['17:30', 'home.inside', 'home'],
        ['19:30', 'home.teras', 'relax'],
        ['20:30', 'home.inside', 'sleep'],
      ],
    }),
  },
  {
    id: 'yusuf',
    name: 'Mas Yusuf',
    address: 'Mas',
    age: 34,
    gender: 'm',
    occupation: 'Ojek driver',
    birthday: '5 Agustus',
    household: 'yusuf',
    traits: ['cheerful', 'sporty'],
    likes: ['football', 'motorbikes', 'family'],
    dislikes: ['market prices'],
    look: { hair: 'short', top: '#2e8b57' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'home'],
        ['06:30', 'ojek.seat', 'work'],
        ['08:00', 'away', 'work'],
        ['09:00', 'ojek.seat', 'work'],
        ['11:30', 'away', 'work'],
        ['12:45', 'ojek.seat', 'work'],
        ['15:00', 'away', 'work'],
        ['16:00', 'ojek.seat', 'work'],
        ['18:00', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['21:30', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['08:00', 'home.teras', 'relax'],
        ['10:00', 'lapangan.bench', 'relax'],
        ['12:00', 'home.inside', 'home'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:40', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['21:30', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [1, 4],
    }),
  },
  {
    id: 'lestari',
    name: 'Mbak Lestari',
    address: 'Mbak',
    age: 31,
    gender: 'f',
    occupation: 'Home catering',
    birthday: '14 Oktober',
    household: 'yusuf',
    traits: ['ambitious', 'caring'],
    likes: ['food', 'work', 'market prices'],
    dislikes: ['football'],
    look: { hair: 'hijab', headwear: '#6b3f5a' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:10', 'home.inside', 'work'],
        ['10:30', 'home.teras', 'work'],
        ['11:30', 'away', 'work'],
        ['12:45', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'relax'],
        ['17:00', 'home.inside', 'home'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['07:30', 'warung.customer', 'shop'],
        ['08:00', 'home.inside', 'work'],
        ['15:30', 'home.teras', 'relax'],
        ['17:00', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'bima',
    name: 'Bima',
    address: 'Dek',
    age: 9,
    gender: 'm',
    occupation: 'SD student',
    birthday: '17 Agustus',
    household: 'yusuf',
    traits: ['curious', 'sporty'],
    likes: ['football', 'food', 'weather'],
    dislikes: ['work'],
    pace: 1.2,
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'home'],
        ['06:40', 'away', 'study'],
        ['12:30', 'home.inside', 'home'],
        ['14:00', 'lapangan.field', 'play'],
        ['16:15', 'kali.fish', 'fish'],
        ['17:30', 'home.inside', 'home'],
        ['20:00', 'home.inside', 'sleep'],
      ],
      sat: [
        ['06:00', 'home.inside', 'sleep'],
        ['07:00', 'lapangan.field', 'play'],
        ['09:30', 'kali.fish', 'fish'],
        ['11:30', 'home.inside', 'home'],
        ['15:00', 'lapangan.field', 'play'],
        ['17:30', 'home.inside', 'home'],
        ['20:00', 'home.inside', 'sleep'],
      ],
    }),
  },
  {
    id: 'putri',
    name: 'Putri',
    address: 'Dek',
    age: 6,
    gender: 'f',
    occupation: 'TK pupil',
    birthday: '2 Desember',
    household: 'yusuf',
    traits: ['shy', 'curious'],
    likes: ['food', 'family', 'music'],
    dislikes: ['weather'],
    pace: 1.1,
    look: { hair: 'bun' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'home'],
        ['06:45', 'away', 'study'],
        ['11:00', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'play'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:15', 'home.inside', 'home'],
        ['19:30', 'home.inside', 'sleep'],
      ],
      sat: [
        ['06:00', 'home.inside', 'sleep'],
        ['08:00', 'home.teras', 'play'],
        ['09:00', 'lapangan.field', 'play'],
        ['11:00', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'play'],
        ['17:15', 'home.inside', 'home'],
        ['19:30', 'home.inside', 'sleep'],
      ],
    }),
  },
  {
    id: 'slamet',
    name: 'Pak Slamet',
    address: 'Pak',
    age: 55,
    gender: 'm',
    occupation: 'Owner of Warkop Berkah',
    birthday: '30 Maret',
    household: 'slamet',
    traits: ['cheerful', 'gossip'],
    likes: ['football', 'gossip', 'food'],
    dislikes: ['weather'],
    look: { hair: 'short', top: '#e2b04a', build: 1.2 },
    schedule: week({
      weekday: [
        ['06:00', 'warkop.owner', 'work'],
        ['10:30', 'home.inside', 'home'],
        ['15:00', 'warkop.owner', 'work'],
        ['23:00', 'home.inside', 'sleep'],
      ],
      jumatan: true,
    }),
  },
  {
    id: 'hartono',
    name: 'Pak Hartono',
    address: 'Pak',
    age: 66,
    gender: 'm',
    occupation: 'Retired civil servant',
    birthday: '1 Juli',
    household: 'hartono',
    traits: ['bookish', 'grumpy'],
    likes: ['old days', 'kampung news', 'religion'],
    dislikes: ['motorbikes', 'music'],
    pace: 0.85,
    look: { hair: 'bald', top: '#c9d6cf', longSleeves: true },
    schedule: week({
      weekday: [
        ['06:00', 'bridge.rail', 'walk'],
        ['07:30', 'warkop.seat', 'chat'],
        ['09:00', 'home.teras', 'study'],
        ['11:40', 'musholla.inside', 'pray'],
        ['12:30', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'study'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['22:00', 'home.inside', 'sleep'],
      ],
      jumatan: true,
    }),
  },
  {
    id: 'joko',
    name: 'Mas Joko',
    address: 'Mas',
    age: 40,
    gender: 'm',
    occupation: 'Bakso cart vendor',
    birthday: '19 November',
    household: 'joko',
    traits: ['cheerful', 'curious'],
    likes: ['food', 'music', 'football'],
    dislikes: ['market prices'],
    look: { hair: 'cap', headwear: '#2f6fb3', top: '#f4f1ea' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:00', 'home.inside', 'work'],
        ['10:00', 'home.teras', 'relax'],
        ['11:00', 'away', 'work'],
        ['16:00', 'bakso.vendor', 'work'],
        ['22:00', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [3, 6],
    }),
  },
  {
    id: 'udin',
    name: 'Bang Udin',
    address: 'Bang',
    age: 38,
    gender: 'm',
    occupation: 'Motorbike mechanic',
    birthday: '8 Juni',
    household: 'udin',
    traits: ['sporty', 'grumpy'],
    likes: ['motorbikes', 'football', 'music'],
    dislikes: ['gossip', 'old days'],
    look: { hair: 'short', top: '#2c3e50', bottom: '#3b3a36' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'sleep'],
        ['07:30', 'home.teras', 'work'],
        ['12:00', 'warung.customer', 'eat'],
        ['12:40', 'home.teras', 'work'],
        ['17:00', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['22:30', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'home.inside', 'sleep'],
        ['09:00', 'home.teras', 'work'],
        ['12:00', 'home.inside', 'home'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:45', 'home.inside', 'home'],
        ['19:30', 'warkop.seat', 'chat'],
        ['22:30', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [1, 4],
    }),
  },
  {
    id: 'rahmat',
    name: 'Pak Rahmat',
    address: 'Pak',
    age: 45,
    gender: 'm',
    occupation: 'Night-shift security guard',
    birthday: '23 Februari',
    household: 'rahmat',
    traits: ['shy', 'caring'],
    likes: ['religion', 'family', 'weather'],
    dislikes: ['gossip'],
    look: { hair: 'short', top: '#1f2a36', bottom: '#1f2a36', longSleeves: true },
    schedule: week({
      weekday: [
        ['06:00', 'away', 'work'],
        ['06:40', 'warkop.seat', 'eat'],
        ['07:30', 'home.inside', 'sleep'],
        ['14:00', 'home.teras', 'relax'],
        ['15:10', 'musholla.inside', 'pray'],
        ['15:45', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'away', 'work'],
      ],
      sat: [
        ['06:00', 'away', 'work'],
        ['06:40', 'warkop.seat', 'eat'],
        ['07:30', 'home.inside', 'sleep'],
        ['14:00', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['20:00', 'warkop.seat', 'chat'],
        ['22:00', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'home.inside', 'sleep'],
        ['09:00', 'home.teras', 'relax'],
        ['11:00', 'kali.fish', 'fish'],
        ['13:00', 'home.inside', 'home'],
        ['15:30', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['19:30', 'away', 'work'],
      ],
      ronda: [6],
    }),
  },
  {
    id: 'yati',
    name: 'Bu Yati',
    address: 'Bu',
    age: 50,
    gender: 'f',
    occupation: 'Tailor',
    birthday: '11 Mei',
    household: 'yati',
    traits: ['gossip', 'cheerful'],
    likes: ['gossip', 'family', 'music'],
    dislikes: ['motorbikes'],
    look: { hair: 'hijab', headwear: '#f0d9b5', top: '#8e44ad' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:15', 'home.teras', 'work'],
        ['11:30', 'home.inside', 'home'],
        ['13:00', 'home.teras', 'work'],
        ['16:00', 'warung.bench', 'chat'],
        ['16:45', 'home.teras', 'chat'],
        ['17:30', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'endang',
    name: 'Bu Endang',
    address: 'Bu',
    age: 47,
    gender: 'f',
    occupation: 'Rents rooms to students (kos)',
    birthday: '6 Maret',
    household: 'endang',
    traits: ['gossip', 'curious'],
    likes: ['gossip', 'kampung news', 'food'],
    dislikes: ['market prices'],
    look: { hair: 'hijab', headwear: '#2f5d8a' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:45', 'home.inside', 'home'],
        ['08:45', 'home.teras', 'work'],
        ['10:00', 'warung.bench', 'chat'],
        ['11:00', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'chat'],
        ['17:30', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'wati',
    name: 'Bu Wati',
    address: 'Bu',
    age: 53,
    gender: 'f',
    occupation: 'Jamu seller',
    birthday: '25 Juli',
    household: 'wati',
    traits: ['caring', 'grumpy'],
    likes: ['food', 'religion', 'old days'],
    dislikes: ['gossip'],
    look: { hair: 'hijab', headwear: '#8a3b2e' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'work'],
        ['06:30', 'away', 'work'],
        ['11:00', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'relax'],
        ['16:00', 'warung.bench', 'chat'],
        ['16:45', 'home.inside', 'home'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['07:00', 'pasar.customer', 'shop'],
        ['08:00', 'home.teras', 'relax'],
        ['11:00', 'home.inside', 'home'],
        ['15:00', 'home.teras', 'relax'],
        ['17:30', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'rizky',
    name: 'Mas Rizky',
    address: 'Mas',
    age: 21,
    gender: 'm',
    occupation: 'Informatics student (anak kos)',
    birthday: '13 Januari',
    household: 'endang',
    traits: ['bookish', 'curious'],
    likes: ['work', 'music', 'football'],
    dislikes: ['religion'],
    pace: 1.05,
    look: { hair: 'short', top: '#2f6fb3' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'sleep'],
        ['07:15', 'warung.customer', 'eat'],
        ['07:45', 'away', 'study'],
        ['16:00', 'home.inside', 'study'],
        ['19:00', 'warkop.seat', 'chat'],
        ['22:00', 'home.inside', 'sleep'],
      ],
      sat: [
        ['06:00', 'home.inside', 'sleep'],
        ['09:30', 'meja.seat', 'eat'],
        ['10:30', 'home.inside', 'study'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:40', 'home.inside', 'home'],
        ['20:00', 'warkop.seat', 'chat'],
        ['23:00', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [5, 0],
    }),
  },
  {
    id: 'nadia',
    name: 'Mbak Nadia',
    address: 'Mbak',
    age: 20,
    gender: 'f',
    occupation: 'Design student (anak kos)',
    birthday: '22 September',
    household: 'endang',
    traits: ['artsy', 'ambitious'],
    likes: ['music', 'work', 'food'],
    dislikes: ['gossip'],
    pace: 1.05,
    look: { hair: 'long', top: '#f2c14e', skirt: false, bottom: '#4a5a6a' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'sleep'],
        ['07:00', 'away', 'study'],
        ['15:30', 'home.teras', 'study'],
        ['17:00', 'home.inside', 'home'],
        ['19:00', 'meja.seat', 'eat'],
        ['20:00', 'home.inside', 'study'],
      ],
      sat: [
        ['06:00', 'home.inside', 'sleep'],
        ['09:00', 'bridge.rail', 'study'],
        ['10:30', 'meja.seat', 'eat'],
        ['11:30', 'home.inside', 'study'],
        ['16:00', 'home.teras', 'study'],
        ['17:30', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'hasan',
    name: 'Ustadz Hasan',
    address: 'Ustadz',
    age: 45,
    gender: 'm',
    occupation: 'Musholla caretaker',
    birthday: '15 April',
    household: 'hasan',
    traits: ['caring', 'bookish'],
    likes: ['religion', 'family', 'old days'],
    dislikes: ['gossip'],
    look: { hair: 'peci', headwear: '#f4f1ea', top: '#f4f1ea', longSleeves: true, skirt: true, bottom: '#3a5a4a' },
    schedule: week({
      weekday: [
        ['06:00', 'musholla.porch', 'work'],
        ['07:00', 'home.inside', 'home'],
        ['09:00', 'musholla.porch', 'work'],
        ['10:00', 'home.teras', 'study'],
        ['11:35', 'musholla.inside', 'pray'],
        ['12:40', 'home.inside', 'home'],
        ['15:00', 'musholla.inside', 'pray'],
        ['15:45', 'home.teras', 'relax'],
        ['17:45', 'musholla.inside', 'pray'],
        ['19:30', 'musholla.porch', 'chat'],
        ['20:00', 'home.inside', 'sleep'],
      ],
    }),
  },
  {
    id: 'karyo',
    name: 'Pak Karyo',
    address: 'Pak',
    age: 42,
    gender: 'm',
    occupation: 'Tukang (handyman)',
    birthday: '4 Oktober',
    household: 'karyo',
    traits: ['caring', 'curious'],
    likes: ['work', 'old days', 'football'],
    dislikes: ['market prices'],
    look: { hair: 'cap', headwear: '#d8392a', top: '#7b8b3a' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'home'],
        ['07:00', 'away', 'work'],
        ['12:00', 'warung.customer', 'eat'],
        ['12:40', 'away', 'work'],
        ['16:30', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
        ['21:00', 'home.inside', 'sleep'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['07:00', 'kebun.plot', 'garden'],
        ['09:00', 'home.teras', 'work'],
        ['12:00', 'home.inside', 'home'],
        ['16:00', 'home.teras', 'relax'],
        ['17:50', 'musholla.inside', 'pray'],
        ['18:40', 'home.inside', 'home'],
      ],
      jumatan: true,
      ronda: [2, 4],
    }),
  },
  {
    id: 'ayu',
    name: 'Mbak Ayu',
    address: 'Mbak',
    age: 29,
    gender: 'f',
    occupation: 'Customer service, works from home',
    birthday: '29 Agustus',
    household: 'ayu',
    traits: ['caring', 'bookish'],
    likes: ['family', 'music', 'food'],
    dislikes: ['football'],
    look: { hair: 'hijab', headwear: '#3a9a73' },
    schedule: week({
      weekday: [
        ['06:00', 'pasar.customer', 'shop'],
        ['07:00', 'home.inside', 'work'],
        ['10:00', 'home.teras', 'relax'],
        ['10:30', 'home.inside', 'work'],
        ['15:30', 'home.teras', 'relax'],
        ['16:30', 'lapangan.bench', 'relax'],
        ['17:15', 'home.inside', 'home'],
      ],
      sun: [
        ['06:00', 'home.inside', 'home'],
        ['07:30', 'bridge.rail', 'walk'],
        ['08:30', 'warung.customer', 'shop'],
        ['09:00', 'home.teras', 'relax'],
        ['11:00', 'home.inside', 'home'],
        ['16:00', 'lapangan.bench', 'relax'],
        ['17:15', 'home.inside', 'home'],
      ],
    }),
  },
  {
    id: 'fajar',
    name: 'Fajar',
    address: 'Dek',
    age: 17,
    gender: 'm',
    occupation: 'SMA student, wants to be a content creator',
    birthday: '7 Desember',
    household: 'yati',
    traits: ['ambitious', 'artsy'],
    likes: ['music', 'motorbikes', 'gossip'],
    dislikes: ['old days'],
    pace: 1.1,
    look: { hair: 'short', top: '#e07a1f' },
    schedule: week({
      weekday: [
        ['06:00', 'home.inside', 'home'],
        ['06:35', 'away', 'study'],
        ['14:30', 'home.inside', 'home'],
        ['15:30', 'bridge.rail', 'work'],
        ['16:30', 'lapangan.bench', 'relax'],
        ['17:30', 'home.inside', 'home'],
        ['19:00', 'meja.seat', 'chat'],
        ['21:00', 'home.inside', 'sleep'],
      ],
      sat: [
        ['06:00', 'home.inside', 'sleep'],
        ['10:00', 'meja.seat', 'chat'],
        ['11:00', 'bridge.rail', 'work'],
        ['12:00', 'home.inside', 'home'],
        ['16:00', 'lapangan.field', 'play'],
        ['17:45', 'home.inside', 'home'],
        ['19:30', 'meja.seat', 'chat'],
        ['22:00', 'home.inside', 'sleep'],
      ],
      jumatan: true,
      ronda: [3, 6],
    }),
  },
];

/** Starting feelings between residents, besides household ties. Includes the two feuds the player can mediate. */
export const TIES: [string, string, number][] = [
  // Ibu-ibu arisan circle.
  ['yati', 'endang', 45],
  ['yati', 'ratna', 40],
  ['endang', 'ratna', 35],
  ['wati', 'yati', 30],
  // Warkop regulars.
  ['slamet', 'hartono', 40],
  ['slamet', 'udin', 35],
  ['slamet', 'rahmat', 30],
  ['slamet', 'yusuf', 30],
  // Elders and old friends.
  ['darto', 'hartono', 35],
  ['darto', 'hasan', 45],
  ['bambang', 'hasan', 40],
  ['bambang', 'darto', 30],
  ['sri', 'ratna', 40],
  ['sri', 'sumi', 45],
  ['karyo', 'darto', 40],
  ['lestari', 'ayu', 35],
  ['rizky', 'nadia', 30],
  ['fajar', 'dimas', 45],
  ['bima', 'dimas', 25],
  ['joko', 'yusuf', 30],
  ['wati', 'sumi', 40],
  // Feud: Udin revs customers' motorbikes late at night; Pak Hartono has complained to Pak RT twice.
  ['udin', 'hartono', -45],
  // Grudge: Bu Endang borrowed money from Bu Wati before Lebaran and has not paid it back.
  ['wati', 'endang', -35],
];

/** Teras visits (spec §8.4 gatherings): neighbours dropping in on each other in the afternoon.
    `@<household>.teras` is that household's teras; when its seats are taken, visitors stand by the pagar. */
const VISITS: [who: string, host: string, days: number[], from: string, to: string][] = [
  // The arisan circle meets on Bu RT's teras.
  ['yati', 'rt', [2, 4], '15:00', '16:30'],
  ['endang', 'rt', [2, 4], '15:00', '16:30'],
  // Old friends on Pak Darto's teras.
  ['hartono', 'darto', [1, 3, 6], '15:15', '16:30'],
  ['wati', 'darto', [1, 4], '15:40', '16:40'],
  ['ayu', 'yusuf', [3], '16:00', '17:00'],
];
for (const [who, host, days, from, to] of VISITS) {
  const def = RESIDENTS.find(r => r.id === who)!;
  for (const dow of days) def.schedule[dow] = overlay(def.schedule[dow], from, to, `@${host}.teras`, 'chat');
}
